//sudprelay_config.h
//DO NOT EDIT THIS FILE DIRECTLY.  It will be overwritten at compile-time by CMake
//
//CMake creates sudprelay_config.h from sudprelay_config.h.in as part of its build process
//When CMake configures this header file the values for 0 and 5 will be replaced.
//  You'll find  variables in the [...].h.in file are replaced with their CMake-contect values when it creates the [...].h file.

//The VERSION is set in the project() call in the top-level CMakeLists.txt file

#define VERSION_MAJOR 0
#define VERSION_MINOR 5
#define VERSION_PATCH 0
#define VERSION_TWEAK 0
